export const RAG_CONFIG = {
  CHUNK_SIZE: 900,
  CHUNK_OVERLAP: 150,
  MIN_CHUNK_CHARS: 100,
  TOP_K: 5,
  NUM_CANDIDATES: 150,
  MIN_SCORE: 0.25,
  EMBED_BATCH_SIZE: 50,
  HISTORY_TURNS_FOR_CONDENSE: 4,
  MAX_FILE_MB: 10,
  MAX_PAGES: 200,
  MAX_CHUNKS_PER_ROOM: 5000,
  INGEST_CONCURRENCY: 2,
  EMBEDDING_MODEL: process.env.EMBEDDING_MODEL || "gemini-embedding-001",
  EMBEDDING_DIMENSIONS: parseInt(process.env.EMBEDDING_DIMENSIONS || "768", 10),
  RAG_VECTOR_INDEX: process.env.RAG_VECTOR_INDEX || "chunk_vector_index",
  RAG_VECTOR_BACKEND: process.env.RAG_VECTOR_BACKEND || "atlas",
  NO_ANSWER_SENTINEL: "NO_ANSWER_IN_CONTEXT",
};

export default RAG_CONFIG;
